[project]
name = "2024-11-28-tragedy-dfs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.0",
    "polars>=1.32.0",
]
